main:
	clang++ -std=c++17 main.cpp -I ../../HEADERS/SDL2/include -L ../../HEADERS/SDL2/lib -lSDL2 -o ./out/main.out
	./out/main.out > ./images/image.ppm

clean: 
	rm ./out/main.out
	rm ./images/image.ppm